## YAML Template for Taxon API testing
# You'll need to edit this after building...
---
cookieName: dataApiTest
username: YOURUSERNAME
password: YOURPASSWORD
loginUrl: https://ci.kbase.us/services/authorization/Sessions/Login
taxonUrl: https://ci.kbase.us/services/data/taxon
assemblyUrl: https://ci.kbase.us/services/data/assembly
genomeAnnotationUrl: https://ci.kbase.us/services/data/annotation
timeout: 10000
testTimeout: 10000